### ISSUE TITLE
혹시 거래우선 지역을 지도/input 로 가능할까요.

### ISSUE THREAD

**Issue by ppleo** [upgle/marketplace#1]
우리나라가 아닌 해외에서 사용시에는 거래 우선지역 선택이나 우선지역에 관한 부분이 한국으로만 제한되여있어서요. 지도로 선택하게 해준다던지 아니면 input으로 간단한 입력으로 변경할수있는 옵션이  필요할 듯합니다.

**Comment by upgle** [comment]
보내주신 거래 우선 지역 부분 개선 피드백 검토하도록 하겠습니다. 
감사합니다

**Comment by upgle** [comment]
Commit: 2f5663bb1410a4936fac928c429a0004c801091c [2f5663b]
Parents: fea17215e5
Author: UPGLE admin@upgle.com
Date: 2015년 3월 14일 오후 4시 25분 13초 GMT+9

거래 우선지역을 사용자가 직접 입력할 수 있도록 개선.
