### ISSUE TITLE
더치트 검색 위젯을 추가하는 것은 어떠한가요?

### ISSUE THREAD

**Issue by allcalc** [upgle/marketplace#3]
더치트도 상업화되었다는 우려도 있지만, 
마땅한 대안(경찰청 넷두루미?)이 없는 상황인 듯 합니다.

그래서 일단은 더치트 위젯을 삽입하는 것이 좋을 듯 하여 문의드립니다.

---

소스코드는 다음 위젯뱅크에 있고
## http://widgetbank.daum.net/widget/view/586

기본 스킨 _read.html 라인#174
 <strong>전화번호 :</strong> <span class="response"></span>

아래에 스크립트 소스 추가하니까 딱 좋게 나오네요.
![image](https://cloud.githubusercontent.com/assets/10527959/6221287/d0d0cfd6-b684-11e4-8540-d32624048360.png)
- 크롬 Adblock 에 차단되는 문제는 있습니다.

**Comment by upgle** [comment]
더치트 위젯은 전화번호를 적어야하고 api형태가 아니라서 고려하지 않았던 부분입니다.
검토해보도록 하겠습니다.

**Comment by upgle** [comment]
다음 위젯뱅크 서비스가 종료되었습니다.
 더치트 위젯 적용은 하지 않도록 하겠습니다. 제안주셔서 감사합니다.
http://blog.daum.net/widgetbank/6975244
