### ISSUE TITLE
1.3에서 상품 수정이 안됩니다.

### ISSUE THREAD

**Issue by socialskyo** [upgle/marketplace#5]
수정 가능으로 변경해도 안됩니다. 공홈 자료실에서도 같은 증상을 호소 하시는 분이 있으십니다.

참고 부탁 드립니다.

**Comment by upgle** [comment]
현재 XE 1.7.11 버전에서 해당 문제가 구현되지 않고 있습니다.
자세한 서버사양 말씀해주시면 감사하겠습니다.

테스트 서버
- PHP 5.3
- XE 1.7.11

**Comment by socialskyo** [comment]
app : Microsoft-IIS/5.0
xe_version : 1.8.0-beta.3
php : 5.3.3
db_type : mysql
use_rewrite : Y
use_db_session : N
use_ssl : none

이렇습니다. 근데 수정 로그남김으로 하니 수정 됩니다. ^^
